### ISSUE TITLE
Vertical Forms

### ISSUE THREAD

**Issue by akshayrawat** [minikomi/Bootstrap-Form-Builder#1]
This project is well done !

Currently, the form builder only supports horizontal forms via `form-horizontal` . It would be nice to also support Bootstrap's default `form-vertical`.

Cheers!

**Comment by minikomi** [comment]
OK. Shouldn't be a problem.

**Comment by minikomi** [comment]
I'm not going to add this.. it's not hard to just delete the class from the rendered form.
