### ISSUE TITLE
elements in Radios / Checkboxes tab lack id

### ISSUE THREAD

**Issue by emmar** [minikomi/Bootstrap-Form-Builder#101]
None of the elements in the Radios / Checkboxes tab do the drag-and-drop correctly, and after some digging, I've found it's because they don't have id's.

How to get there: 
1. select the "Radios / Checkboxes" tab
2. click any of the elements
3. drag it to the form box on the left
4. take finger off the mouse button (mouseUp)

What it looks like: 
- click and drag look good
- element gets added to form
- popover box is "stuck" to the cursor until you click again

In chrome javascript console, you get the error "Uncaught TypeError: Cannot read property 'value' of undefined."  It refers you to the following line `var t=e.attributes.fields.id.value;`

**Comment by dptole** [comment]
The pull request #103 may fix this issue but I've seen another one.
When the radios (inline or multiple) are pushed to the form they share the same group name called `radio`, which causes the previously inserted radios to be unfocused.

**Comment by minikomi** [comment]
Thank you @dptole & @emmar. I added in the relevant field and adjusted the templates.. Can you check if it's fixed the problem for you and close if so?

I didn't use the pull request as I'd rather fix the source than the compiled js.

**Comment by dptole** [comment]
@minikomi it's fixed for me, thanks

**Comment by emmar** [comment]
I tried it on the demo, and it works great.  Thanks @dptole and @minikomi!
