### ISSUE TITLE
Bootstrap 3

### ISSUE THREAD

**Issue by stickypages** [minikomi/Bootstrap-Form-Builder#102]
Hey thoughts or plans to move into Bootstrap 3?

**Comment by tanwaniniranjan** [comment]
Please look for the bootstrap 3 version here

https://bountify.co/new-version-of-bootstrap-formbuilder-in-v3

**Comment by stickypages** [comment]
Ahhh yeah thanks for the notice. I see the 'winning' solution isn't available for download...
I will try the others.

Thanks

**Comment by tanwaniniranjan** [comment]
Ok, So I am gonna keep this copy for a while: http://www.small2big.in/Bootstrap-3-Drag-n-Drop-Form-Maker.zip

**Comment by stickypages** [comment]
Okay great thanks.

**Comment by jangondol** [comment]
If the above link ever goes away, [here's the permalink](https://web.archive.org/web/20150517100919/http://www.small2big.in/Bootstrap-3-Drag-n-Drop-Form-Maker.zip).

**Comment by tanwaniniranjan** [comment]
Haha, archive! 👍🏻

**Comment by ghost** [comment]
Hi Above. The solution you posted is that having a touch support for drag and drop ??

**Comment by tanwaniniranjan** [comment]
no

**Comment by ghost** [comment]
Hi 

Can we add a support for dynamically adding column structure to the form builder.?
Like the below guy has done. 

http://demos.anupshinde.com/form-builder-part2-1_kevin_d/index.html

**Comment by ghost** [comment]
@tanwaniniranjan  Hi have you got any success in edit form reload by passing Json or any other method ??
I need help in that

**Comment by tanwaniniranjan** [comment]
Honestly, haven't tried. Needed it for an old project, but the module was removed.

**Comment by tonytlwu** [comment]
Based on the *Getting Started* guide for [Fuel UX's Form Builder](http://getfuelux.com/formbuilder.html), it looks like [they support Bootstrap 3](http://getfuelux.com/getting-started.html).
