### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by karthikagile** [minikomi/Bootstrap-Form-Builder#104]
Hi,

I wanted to add feature to edit a form, already built using this form builder.

If we have the form's html code, or form field json saved, need to convert to form fields which can be updated directly, without having to build the whole form again.

Any info on how to proceed would be of great help.

Thanks.

**Comment by shethnc** [comment]
I have same question. Can it be done ?

**Comment by tanwaniniranjan** [comment]
We will need the source code! then it can be done.. if we get it, i'll try and finish it up in my free time.

**Comment by shethnc** [comment]
ok Cool. Will be waiting for it to be finished.

Thanks

**Comment by tanwaniniranjan** [comment]
I need the non-built source code for that! might have to ask the author!

**Comment by minikomi** [comment]
Outside the scope of this repo. Please fork and add yourself.
