### ISSUE TITLE
Two columns

### ISSUE THREAD

**Issue by suenot** [minikomi/Bootstrap-Form-Builder#11]
The service is great! But I often work with two columns form. It would be great if you implemented this function.

**Comment by minikomi** [comment]
You mean a set of combined inline elements? Eg. Two text inputs, an input and select etc.

**Comment by cassdsghxw** [comment]
that means: 

Form Name

column1(label + field) [blank space] column2(label + field) 
column1(label + field) [blank space] column2(label + field) 
column1(label + field) [blank space] column2(label + field) 
column1(label + field) [blank space] column2(label + field) 
column1(label + field) [blank space] column2(label + field) 

```
                         Submit
```

**Comment by minikomi** [comment]
No, unfortunately that would require pretty extensive changes to the drag & drop.
Supporting two dimensions as it were.
Sorry but apart from perhaps offering some pre-made two column options, that's outside the scope of this quick & dirty tool.

**Comment by cassdsghxw** [comment]
ok, tks for you reply; i'm try to rewrite the code to implement my requirement....
