### ISSUE TITLE
Form Builder Edit Functionality

### ISSUE THREAD

**Issue by hasibul2363** [minikomi/Bootstrap-Form-Builder#111]
Is there any functionality available so that user can modify their existing template?
If yes then can you kindly share how we can do this?

If no can you give some hints so that we can implement it by modifying or extending your code.
Waiting for your help.

Thanks for sharing wonderful work.

**Comment by hasibul2363** [comment]
found solution on
https://github.com/minikomi/Bootstrap-Form-Builder/issues/40#issuecomment-24131496

**Comment by ivantowers** [comment]
Hello, how do you do it? any hint? thanks!
