### ISSUE TITLE
How i can change control name

### ISSUE THREAD

**Issue by hasibul2363** [minikomi/Bootstrap-Form-Builder#112]
I found that control name was taken from yml files.
If i want to change control name programmatically instead of yam file then how i can achieve this.

Consider right now it is showing control name "Text Input" how i can change it to Text Box?
Waiting for your help.

**Comment by zeeshan4971** [comment]
Dafa hoja kuttay tu kiya karaya ga is ka

**Comment by hasibul2363** [comment]
@zeeshan4971 hi do you have any mental disorder problem?

**Comment by zeeshan4971** [comment]
bharway teri maa ki choot hai tu programming kar kay apni gand kun mararaha hai behchod apni shakal dekhi hai ja jakay sabzi bech tu isi like hai

**Comment by dptole** [comment]
@hasibul2363 I'm not sure if I understood your question but when you drag the component to the form area, and click on it, you have a field called **Label Text**. I think you should just change that value.
