### ISSUE TITLE
Create JSON from form

### ISSUE THREAD

**Issue by Nehace40** [minikomi/Bootstrap-Form-Builder#119]
To minikomi

in https://github.com/minikomi/Bootstrap-Form-Builder/issues/40#

in above you give ans in that you said that add some code in my-form.js
Add:

 this.collection.on("add", this.toJson, this);
 this.collection.on("remove", this.toJson, this);
 this.collection.on("change", this.toJson, this);

, toJson: function() {
 console.log(this.collection.toJSON());

}
Open the console, and look at the output. i m follow ur instruction but in console there is no JSON object

**Comment by minikomi** [comment]
Did you build the script using r.js? Or change the index.html to use the unbuilt version?

**Comment by XiaoqinLI** [comment]
@minikomi can you explain a little bit more how to render form as Json object instead of html markups?
I check issues like #40 and #63 and others, but none of them explains it explicitly.
Thank you very much.

**Comment by XiaoqinLI** [comment]
I was able to output json obj in console, but how to see them in "rendered view"?
