### ISSUE TITLE
What is different between main.js and main-built.js

### ISSUE THREAD

**Issue by pacozaa** [minikomi/Bootstrap-Form-Builder#127]
1.I never use requirejs before and I try switch between main.js and main-built.js and I just find that main.js can not render page and main-built.js is OK.

2.I try to follow the README and change a little bit of code then use r.js to compile(maybe) and I can edit the form builder my use 

<script data-main="assets/js/main-built.js" src="assets/js/lib/require.js" ></script>

but not 

<script data-main="assets/js/main.js" src="assets/js/lib/require.js" ></script>

So I think in README you write that I should use main.js for the compiled code version not the another way around like I meet.

Thank you

**Comment by minikomi** [comment]
Read http://requirejs.org/ and try again
