### ISSUE TITLE
development & debugging

### ISSUE THREAD

**Issue by unosbm65** [minikomi/Bootstrap-Form-Builder#129]
Hi
For development & debugging I changed the data-main  to point at `assets/js/main.js` but when I open my html file, it doesn't render the html . 

How can I compile files with require.js ?
And how can I develop when the case is this  "script data-main="assets/js/main.js" src="assets/js/lib/require.js"

**Comment by minikomi** [comment]
You can learn about require.js here:

http://requirejs.org/
