### ISSUE TITLE
Radio buttons in Chrome browser

### ISSUE THREAD

**Issue by truks** [minikomi/Bootstrap-Form-Builder#13]
Changing the values for the text/values for radio buttons fails to apply using google chrome browser.

Sometimes, the first attempt will succeed, and then successive attempts will fail.

**Comment by minikomi** [comment]
I'm having trouble reproducing this. What did you enter for your values? Can you give me the steps it took to make it break?

**Comment by truks** [comment]
Adam,

```
Thanks for the reply.

Yes, I'm using chrome on XP Pro SP3. 
The chrome version is 23.0.1271.97 m.

I saw the issue when I added any radio set to a form. I downloaded the
```

windows zip package and extracted it intact, and was using the index.html.

```
The first time I went to change the options, the change would work, but
```

subsequent attempts to change the options would fail.

```
This morning, I am working with it again, and I am not seeing the same
```

behavior.

```
Perhaps my system had some instability last night that the boot this
```

morning has resolved.

```
In any case, I was only seeing the issue with the radio elements, and it
```

was only the options with those (I could always change the label and group,
even when the options issue was happening).

```
I will keep an eye on this as I use it and try to narrow down more info
```

if I see it happening again.

```
Since you are a developer with this project, I would like to ask you
```

another, unrelated question.

```
I am wanting to modify this source for my needs, specifically to change
```

the output (the result in the generated source tab)

```
(no, I had not edited the source when I was seeing the issue, I have not
```

tried to change it yet)

```
I would like to change the output into an encoding I am working on to
```

use for another project.

```
I see in fb.js in the genSource function where the output for radios and
```

checkboxes is generated, but I am wondering if you will give me a pointer
and/or any insight to where the other elements' source is generated.

```
I know eventually I could figure it out, but I figure you are already
```

much more intimate with the code, and could likely save me a bunch of time.

```
Again, thanks for the reply, and thanks for any additional help you can
```

give.

Kurt Stevens

-----Original Message-----

**Comment by minikomi** [comment]
Thanks Kurt, let me know if you see it again. Also, if possible, when you see it happening can you let me know if there's any message in the Javascript console? It might be throwing an error which will make it easier to track down.

The code is not well organized, but the two long if / else trees are where you want to be looking, along with the "vartype" data attribute which tells the function how to create the item from the popover values and vice versa.

**Comment by truks** [comment]
Thanks much for the pointer, Adam. That should help me a lot in what I want
to do.

When I was having the issue earlier, I had chrome's javascript console open,
and I did set a breakpoint in the code to try to see what was going on, but
I didn't have the time to put into it then.

I do know, though, that there were no error messages.

Ok, Adam, it is doing it again right now. 

Here is exactly what I did:
1. open index.html in chrome.
2. select radio tab.
3. drag an inline radio group to the form (I notice here that in my browser,
   the first radio is checked, and it stays checked when I change the options.
   the inline radio is the only object that has an item checked).
4. change the options (I went from 1 2 3 to Pass Fail, and this succeeds).
5. drag a radio buttons object (not inline) into the form below the existing
   radio group. (when I drop the new object into the form, the first radio
   group checked item becomes unchecked, and the first radio button in the new
   group becomes checked!!! Interesting.).
6. attempt to change the items in the new group, can change the label text,
   cannot change the button items.

So, since this is directly after a fresh boot, directly after opening the
browser, I would guess that this is real after all.

I did this with the js console open, no error messages.

I just refreshed the browser, and now I can't get the same result.

That's all I know at this point, but I forgot to mention the 'jumping
selected radio' thing (it seems like the selected radio jumps from one group
to the next, visually, when I drop the new group).

I likely won't have time to work with this more today, but I will be working
on it in the future, and I will definitely be on the lookout for anything
more I can find out if I see this again.

Thanks for your work on this project, it definitely is a useful one, and I
appreciate your efforts.

Kurt Stevens

  -----Original Message-----

**Comment by minikomi** [comment]
Hmm.. Maybe this has to do with the "group" name being the same.. try changing the group name of the inline radios before adding the others.

**Comment by truks** [comment]
If I change the group name, the first radio stays selected, and the first
radio in the second group is selected as well.

Not seeing the issue today (yet).

-----Original Message-----

**Comment by minikomi** [comment]
Thanks for taking the time to give a detailed description. I'll look into
it as soon as I can.

On Thursday, December 20, 2012, truks wrote:

> Thanks much for the pointer, Adam. That should help me a lot in what I
> want
> to do.
> 
> When I was having the issue earlier, I had chrome's javascript console
> open,
> and I did set a breakpoint in the code to try to see what was going on,
> but
> I didn't have the time to put into it then.
> 
> I do know, though, that there were no error messages.
> 
> Ok, Adam, it is doing it again right now.
> 
> Here is exactly what I did:
> 1. open index.html in chrome.
> 2. select radio tab.
> 3. drag an inline radio group to the form (I notice here that in my
>    browser,
>    the first radio is checked, and it stays checked when I change the
>    options.
>    the inline radio is the only object that has an item checked).
> 4. change the options (I went from 1 2 3 to Pass Fail, and this succeeds).
> 5. drag a radio buttons object (not inline) into the form below the
>    existing
>    radio group. (when I drop the new object into the form, the first radio
>    group checked item becomes unchecked, and the first radio button in the
>    new
>    group becomes checked!!! Interesting.).
> 6. attempt to change the items in the new group, can change the label
>    text,
>    cannot change the button items.
> 
> So, since this is directly after a fresh boot, directly after opening the
> browser, I would guess that this is real after all.
> 
> I did this with the js console open, no error messages.
> 
> I just refreshed the browser, and now I can't get the same result.
> 
> That's all I know at this point, but I forgot to mention the 'jumping
> selected radio' thing (it seems like the selected radio jumps from one
> group
> to the next, visually, when I drop the new group).
> 
> I likely won't have time to work with this more today, but I will be
> working
> on it in the future, and I will definitely be on the lookout for anything
> more I can find out if I see this again.
> 
> Thanks for your work on this project, it definitely is a useful one, and I
> appreciate your efforts.
> 
> Kurt Stevens
> 
> -----Original Message-----
> From: Adam Moore [mailto:notifications@github.com <javascript:_e({},
> 'cvml', 'notifications@github.com');>]
> Sent: Monday, December 17, 2012 9:03 PM
> To: minikomi/Bootstrap-Form-Builder
> Cc: truks
> Subject: Re: [Bootstrap-Form-Builder] Radio buttons in Chrome browser
> (#13)
> 
> Thanks Kurt, let me know if you see it again. Also, if possible, when you
> see it happening can you let me know if there's any message in the
> Javascript console? It might be throwing an error which will make it
> easier
> to track down.
> 
> The code is not well organized, but the two long if / else trees are where
> you want to be looking, along with the "vartype" data attribute which
> tells
> the function how to create the item from the popover values and vice
> versa.
> 
> ## 
> 
> Reply to this email directly or view
> <
> https://github.com/minikomi/Bootstrap-Form-Builder/issues/13#issuecomment-1
> 1471045> it on GitHub.
> 
> <
> https://github.com/notifications/beacon/T3izrWDRT7aPvJfy0ZccLCJgtrP3vxe4duR
> PVuWa8QhiMN67aPaiRYx4Vm0oMqdu.gif>
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/13#issuecomment-11543914.

## 

----=^.^=---

**Comment by nfvs** [comment]
FWIW, this is very likely related to issue #15. It should be fixed now.

**Comment by truks** [comment]
OK, thanks.

Great product!

-----Original Message-----

**Comment by minikomi** [comment]
#15 seems to have solved it. I'll close this for now - please reopen if you see the behavior again
