### ISSUE TITLE
drag and drop doesnt work when chrome window is maximized

### ISSUE THREAD

**Issue by ghost** [minikomi/Bootstrap-Form-Builder#131]
My browser is `Chromium 45.0.2454.85 Built on Ubuntu 14.04, running on LinuxMint 17.2`

When I maximize the browser, the drag and drop doesn't work. The dragging is fine, but the option to drop never shows up.

When I make the browser half the screen width, the dragging and dropping works. 

I am basing this observation off `http://bootsnipp.com/forms`. Please let me know if there's a different repo I should put the issue on.

**Comment by minikomi** [comment]
I only maintain the version here:

https://minikomi.github.io/Bootstrap-Form-Builder/

Does that work? @MaxPleaner
