### ISSUE TITLE
"Clone" an input already in fieldset?

### ISSUE THREAD

**Issue by bfblackjack** [minikomi/Bootstrap-Form-Builder#138]
After dragging an input into the form fieldset, how would I be able to actually CLONE this specific input?

I tried jquery -> $('#target fieldset').append($(element).parent().parent().closest("div").clone()).html();

This DOES clone it but does NOT save it. As soon as you click anywhere else the newly cloned input disappears.

**Comment by minikomi** [comment]
Bugs only thanks.
