### ISSUE TITLE
Not possible to view the saved form html and edit

### ISSUE THREAD

**Issue by tareqalam** [minikomi/Bootstrap-Form-Builder#141]
I am trying to save the rendered form html to database. then trying to edit the form, but my problem is I can not load the form html on load of page. would be nice to solve this then this generated form can be saved in database and can be edited later if necessary. thanks a lot for the great work you have done!

**Comment by KelsoField** [comment]
I am also working on this after coming across this fork yesterday.
I want to "one click" save the output to a database and then be able to reload if required.
Of course this is just the form, any actions would be separate (but also working on a form action element)
I have successfully converted over to BS3 and working under .php and can save the html to a database with a new button.
Retrieving the output html is the easy part, but the builder uses JSON array to populate.
Capturing this alongside the output is the key and will update this once I have solved it.

**Comment by minikomi** [comment]
Outside scope of this project.
