### ISSUE TITLE
Can't see all controls of the first field

### ISSUE THREAD

**Issue by naoliv** [minikomi/Bootstrap-Form-Builder#143]
Clicking at the first field (`Nome`) to see/edit its properties:

![](https://cloud.githubusercontent.com/assets/982338/23621905/475d181e-027b-11e7-9fe4-370900fc5044.png)

See how some part of the properties dialog is hidden behind the top part.

**Comment by minikomi** [comment]
I do not maintain this site. Please take it up with the site owner.
