### ISSUE TITLE
builder breaks when used inside a modal window.

### ISSUE THREAD

**Issue by ejvalmores** [minikomi/Bootstrap-Form-Builder#16]
Dragging / Dropping of an element seems to be happening behind the modal window.  Is there a workaround to make this work on a modal window? thanks!

**Comment by minikomi** [comment]
I don't understand what you're asking. The site has no modal windows.

**Comment by jogarriot** [comment]
@minikomi what he means is when you host the formbuilder inside the modal window you the drag-drop wont work. 

When I use FF it inserts the temp form before the title. When using IE it simply will not show.
![ff](https://f.cloud.github.com/assets/6693069/2179145/7ff77956-9692-11e3-94a4-2d8eeec94422.png)
![ie](https://f.cloud.github.com/assets/6693069/2179146/80108a86-9692-11e3-8dbc-a1309bceefd4.png)
