### ISSUE TITLE
Loading form form the saved source code

### ISSUE THREAD

**Issue by sanjaysparx** [minikomi/Bootstrap-Form-Builder#17]
Hi,

I'm using "Bootstrap Form Builder" for an application & saving data (Source code ) in DB. Now I want to edit the "saved form" through "Form builder" interface. But not sure how to load  "DB source" so that I can edit/update the form.

Could you please help me out?

Thanks,

**Comment by aaroncastanos** [comment]
Thank you for the email.&nbsp; Please be aware that my email address has recently changed to aaron.castanos@connectedbusiness.com.&nbsp;
The email you sent will be forwarded to my new email address.

Thank you,

Aaron Casta&ntilde;os

**Comment by sanjaysparx** [comment]
Thanks Aaron! Please look into my issue & advice.

Kindest Regards,
Sanjay

**Comment by frutik** [comment]
I have same problem

**Comment by minikomi** [comment]
Not going to add this. If you want, you can fork and have it so the builder exports / imports the my-form collection as JSON.

**Comment by ankurngm** [comment]
If anyone of you suceeded in accomplishing it, can you please share the snippet. I need to do the following?
1. Create form using plugin
2. Save the generated collection as json/yaml in database 
3. Re-create the form using the save information.
- Thanks.

**Comment by qfard** [comment]
ankurngm,

did you find a solution, without saving it and reusing it, it would do me any good...

TIA

**Comment by ankurngm** [comment]
qfard - No I couldn't, instead created myself in different technology.

**Comment by ibanez0r** [comment]
http://api.jquery.com/serialize/

**Comment by qfard** [comment]
Ankurmgn,

Thanks for the reply.

May I ask what approach/technology did you use to accomplish this?

**Comment by ankurngm** [comment]
Used AngularJs with Drag n  Drop plugin
