### ISSUE TITLE
New jquery seems to break this form builder =(

### ISSUE THREAD

**Issue by msurguy** [minikomi/Bootstrap-Form-Builder#18]
Can't quite pinpoint the source of the problem but when using new jquery the form builder stops working - more specifically cannot edit a single field - the popover displays the actual HTML instead of browser parsed HTML.

**Comment by craighooghiem** [comment]
I believe this is an issue with the new version of Bootstrap, because they added an html boolean value to the JS.
http://twitter.github.com/bootstrap/javascript.html#popovers 

Now you have to add html:true to the popover in order for the HTML to be parsed, as it defaults to false.

**Comment by msurguy** [comment]
Oh, will try that, that must be it! 
Thanks @craighooghiem !!! You saved my day =)

**Comment by craighooghiem** [comment]
No problem. Been there, had that issue, fixed it.
I was going to file a pull-request but I'm about 9 light years away from this build now.
I wrapped mine up into a fuelPHP CMS and it's grossly modified.

**Comment by msurguy** [comment]
I see that there is a Backbone branch in this repo now, hopefully that will be available soon =) 

Is your FuelPHP cms module open source? I want to make something like that for Laravel PHP framework too =)

**Comment by craighooghiem** [comment]
No it's not and it won't ever be.
I'm moving all my projects to Laravel and letting this one die a slow death. 

It's a block-based CMS, similar in concept to PyroCMS, but not similar in execution at all.
However, with PyroCMS moving to laravel a bunch of great changes are happening for CMS therein.

**Comment by msurguy** [comment]
Cool! 

Do you have co-founders or collaborators on the CMS? 
I am also developing a CMS but with different focus. 

This form builder was just for Bootsnipp.com website that I made with Laravel long ago =)

**Comment by craighooghiem** [comment]
I work for a company (Vicimus in Ontario, Canada) and I'm the manager for everything development. 
I built the CMS myself and no one else has touched it yet. It was made for clients to be able to manage the websites we create for them, so it serves it's purpose, but not much more.
