### ISSUE TITLE
Cannot drop components in IE8

### ISSUE THREAD

**Issue by dokechin** [minikomi/Bootstrap-Form-Builder#19]
After major version up, I cannot drop components to form pallet.
Befor version I cound.

**Comment by dokechin** [comment]
IE log is below

オブジェクトでサポートされていないプロパティまたはメソッドです。
main-built.js 行26文字172609

render:function(){this.$el.empty();var n=this;
                                                       ^

**Comment by minikomi** [comment]
OK I think I know what this is. There's a [].map(function(){}) in there
which I changed to use _.map([], function(){})

Can you test here: http://poyo.co/forms/

On Mon, Mar 18, 2013 at 6:02 PM, Tetsuya Tatsumi
notifications@github.comwrote:

> IE log is below
> 
> $B%*%V%8%'%/%H$G%5%]!<%H$5$l$F$$$J$$%W%m%Q%F%#$^$?$O%a%=%C%I$G$9!#(B
> main-built.js $B9T(B26$BJ8;z(B172609
> 
> render:function(){this.$el.empty();var n=this;
> ^
> 
> $B!=(B
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/19#issuecomment-15044505
> .

## 

----=^.^=---

**Comment by dokechin** [comment]
Very Good, I can do it.

And I found other problem, this also IE only,
After drop Radios  or checkboxes, and singble button and double button, all the text is selected.
Other Components are going well.

**Comment by minikomi** [comment]
OK, i disabled selection for $('form') .. can you check again?

On Mon, Mar 18, 2013 at 6:33 PM, Tetsuya Tatsumi
notifications@github.comwrote:

> Very Good, I can do it.
> 
> And I found other problem, this also IE only,
> After drop Radios or checkboxes, and singble button and double button, all
> the text is selected.
> Other Components are going well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/19#issuecomment-15045616
> .

## 

----=^.^=---

**Comment by dokechin** [comment]
I checked agein, but not mended.

**Comment by minikomi** [comment]
Please open another issue with details of that bug.
