### ISSUE TITLE
main-built.js scripts described in index.html

### ISSUE THREAD

**Issue by dokechin** [minikomi/Bootstrap-Form-Builder#20]
Hi,

in index.html describes belows,

```
<script data-main="assets/js/main-built.js" src="assets/js/lib/require.js" ></script>
```

In source path , main-build.js have not included.
to describe main.js is not currect ??

**Comment by minikomi** [comment]
I'm building everything into main-built using r.js . I'll add a description
of this and close this issue thanks.

On Monday, March 18, 2013, Tetsuya Tatsumi wrote:

> Hi,
> 
> in index.html describes belows,
> 
> <script data-main="assets/js/main-built.js" src="assets/js/lib/require.js" ></script>
> 
> In source path , main-build.js have not included.
> to describe main.js is not currect ??
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/20
> .

## 

----=^.^=---
