### ISSUE TITLE
After drop, all components chage to be selectable state.

### ISSUE THREAD

**Issue by dokechin** [minikomi/Bootstrap-Form-Builder#21]
IE only,
After drop Radios or checkboxes, and singble button and double button, all the text will be a selectable state.
Other Components are going well. 

Image file added please show detail.

**Comment by minikomi** [comment]
Thanks, I can't see your image though can you re-attatch?

**Comment by dokechin** [comment]
Oh, reatach this.
![image](https://f.cloud.github.com/assets/2212043/273966/056da22a-9042-11e2-8a3e-f9baca7b856d.PNG)

**Comment by minikomi** [comment]
Can you check again please? On http://bootstrap-forms.heroku.com.
It fixed it for most cases, but still happens occasionally. Still trying to pin down the cause.

**Comment by dokechin** [comment]
Hi,
I found #19 issued has not merged , please confirm again.

**Comment by minikomi** [comment]
Thanks. There was another place where I'd used .map, and also .trim for a string which was not working in IE8.

**Comment by dokechin** [comment]
Excellent !! I tryed again, and I found it was fixed.
Thank you very much.
