### ISSUE TITLE
After reordering , all the component will change to selectable In IE

### ISSUE THREAD

**Issue by dokechin** [minikomi/Bootstrap-Form-Builder#22]
Hi, I found other problem.
This case is IE only.
After putting component from pallet to the canvas,
Reorderring components in canvas, by drag and drop operation.
All the component change to selectable state.

**Comment by dokechin** [comment]
Hi !
I tryed agein at new version. This proglem have fixed.

**Comment by minikomi** [comment]
Great! I changed some selection preventing CSS. :cat2:
