### ISSUE TITLE
Can't copy code from rendered source

### ISSUE THREAD

**Issue by php-coder** [minikomi/Bootstrap-Form-Builder#28]
It's strange that I can't copy rendered source from textarea: it disappears from clipboard. I can reproduce this in Iceweasel 15.0.1 (Debian) and Firefox 19.0.2 (Ubuntu)

**Comment by minikomi** [comment]
@php-coder  Can you check again now?

**Comment by minikomi** [comment]
53a17187d204b7d8cd6a110cda863af62c8ed3b0

**Comment by php-coder** [comment]
Thank you, now it works!
