### ISSUE TITLE
Form element's properties?

### ISSUE THREAD

**Issue by rizqyhi** [minikomi/Bootstrap-Form-Builder#32]
Hey, I'd really looking for such plugin. Is there any plan to add features that allow us to customize the form elements's properties too? So we can add, for example, the name attribute for the element.
Nice work, thanks.

**Comment by minikomi** [comment]
Clicking on a form element will give you a popover allowing you to edit some properties. If you need more properties, please fork the project and add them to the yaml / underscore templates and recompile.

**Comment by rizqyhi** [comment]
sorry, my mistake, I didn't noticed them.
