### ISSUE TITLE
Choose which class to add instead of default "input-xlarge"

### ISSUE THREAD

**Issue by ivansammartino** [minikomi/Bootstrap-Form-Builder#33]
Thanks, the Form Builder saves me lot of time!!! :-)
Please, can you add the option to choose which class to add instead of the default "input-xlarge", even for textareas?
Many many thanks!

**Comment by minikomi** [comment]
Yep it can be done. A dropdown to select sizes?

On Wed, May 8, 2013 at 2:49 PM, Ivan notifications@github.com wrote:

> Thanks, the Form Builder saves me lot of time!!! :-)
> Please, can you add the option to choose which class to add instead of the
> default "input-xlarge", even for textareas?
> Many many thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/33
> .

## 

----=^.^=---

**Comment by ivansammartino** [comment]
Yes, thanks! Sizes (input-mini, input-small, etc.) and classes (span1, span2, etc.), please
Really, this form builder is amazing!!!

**Comment by minikomi** [comment]
I think span1 - 12 don't really work well with this form builder.. since
the actual form itself is span6. I'll add the other size classes though.
Thanks!

**Comment by ivansammartino** [comment]
NP! I'll later do a "search and replace" in my text editor in case I'd need to use spans :-)

**Comment by minikomi** [comment]
OK! Give it a go! :point_right: : 58f7120bc0ffd1adb38ba6491104ca106fc1f581

:octocat: :cactus:

**Comment by ivansammartino** [comment]
Many thanks! I noticed that XXLarge expands too much in the Form Builder, but functionalities are untouched (I can still drag & drop)
Maybe (but it's NOT crucial, it's still great now!!!) you could drop the larger sizes and fill in the smallest ones even with span\* (say, 'til span4 or span5)...

**Comment by minikomi** [comment]
Yeah, unfortunately I noticed that too..

I could add a max-width / overflow hidden to the target form but it still
looks a bit weird.
Maybe that's the best I can do with a span6 target form!

On Fri, May 10, 2013 at 8:57 PM, Ivan notifications@github.com wrote:

> Many thanks! I noticed that XXLarge expands too much in the Form Builder,
> but functionalities are untouched (I can still drag & drop)
> Maybe (but it's NOT crucial, it's still great now!!!) you could drop the
> larger sizes and fill in the smallest ones even with span\* (say, 'til span4
> or span5)...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/33#issuecomment-17716480
> .

## 

----=^.^=---

**Comment by minikomi** [comment]
Just added some cosmetic fixes for this. Best I can do I think!

On Fri, May 10, 2013 at 9:01 PM, adam moore nerdfunk@gmail.com wrote:

> Yeah, unfortunately I noticed that too..
> 
> I could add a max-width / overflow hidden to the target form but it still
> looks a bit weird.
> Maybe that's the best I can do with a span6 target form!
> 
> On Fri, May 10, 2013 at 8:57 PM, Ivan notifications@github.com wrote:
> 
> > Many thanks! I noticed that XXLarge expands too much in the Form Builder,
> > but functionalities are untouched (I can still drag & drop)
> > Maybe (but it's NOT crucial, it's still great now!!!) you could drop the
> > larger sizes and fill in the smallest ones even with span\* (say, 'til span4
> > or span5)...
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/33#issuecomment-17716480
> > .
> 
> ## 
> 
> ----=^.^=---

## 

----=^.^=---
