### ISSUE TITLE
Add "for" attribute in "control-label"s

### ISSUE THREAD

**Issue by ivansammartino** [minikomi/Bootstrap-Form-Builder#34]
Please, can you add the "for" attribute (tied to relative input field) for "control-label"s?
Many thanks :-)

**Comment by minikomi** [comment]
Yep makes sense! Thanks I'll add it.

On Wed, May 8, 2013 at 2:55 PM, Ivan notifications@github.com wrote:

> Please, can you add the "for" attribute (tied to relative input field) for
> "control-label"s?
> Many thanks :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/34
> .

## 

----=^.^=---

**Comment by ivansammartino** [comment]
Thanks! :-)

**Comment by minikomi** [comment]
Check it out :point_right:  ec78d6e4c02f7adaac13e64b8ff74131aade1202 

I also added it for checkboxes :checkered_flag:

**Comment by ivansammartino** [comment]
Very nice, thanks!
