### ISSUE TITLE
Adding new Form elements ?

### ISSUE THREAD

**Issue by simith** [minikomi/Bootstrap-Form-Builder#35]
Thanks for the wonderful form Builder for Bootstrap, i would like to use it in my project as a Form Builder, i'm new to Backbone.js, what is the process for adding new form elemen (like for example a new GUI Element) into the Form Builder's existing list of GUI elements. Please let  me know how to get started with that ? Thank you.

**Comment by minikomi** [comment]
Ah, I should add this to the readme:
- In the [js/data/yaml folder](https://github.com/minikomi/Bootstrap-Form-Builder/tree/gh-pages/assets/js/data/yaml) are yaml files each, of which corresponds to a tab in the form builder.
- If you just want to add a new element you need to:
  - describe it in one of these files
  - parse the yaml to json using parse.rb in the same folder
  - create a corresponding template in the [templates/snippet directory](https://github.com/minikomi/Bootstrap-Form-Builder/tree/gh-pages/assets/js/templates/snippet)
  - add the template to [snippet-templates.js](https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/templates/snippet/snippet-templates.js)
- If you want to add a new tab, you'll also need to adjust the [app.js file](https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/app.js) to make sure the tab is loaded.

Adding a new type for the popover is much more involved. I'd recommend looking at how the others are implemented if you want to go down this route.

This isn't really an "issue" as such, so I'll add a note on the readme and close this.

**Comment by simith** [comment]
Thank you for that and the great stuff you have built.

**Comment by minikomi** [comment]
:blush:
