### ISSUE TITLE
Development mode

### ISSUE THREAD

**Issue by Keeo** [minikomi/Bootstrap-Form-Builder#39]
Hi,
i am not able to switch to development mode. One would simply assume that clone repository and switch script tag to this 

``` html
<script data-main="assets/js/main.js" src="assets/js/lib/require.js" ></script>
```

would be enough but it doesn't work.
Is it wrong or is there something missing in the readme?

**Comment by minikomi** [comment]
Are you running a server from the root directory? eg python -m
SimpleHTTPServer

On Wednesday, July 3, 2013, Keeo wrote:

> Hi,
> i am not able to switch to development mode. One would simply assume that
> clone repository and switch script to this
> 
> <script data-main="assets/js/main.js" src="assets/js/lib/require.js" ></script>
> 
> would be enough but it doesn't work.
> Is it wrong or is there something missing in the readme?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/39
> .

## 

----=^.^=---

**Comment by Keeo** [comment]
Oh, that was the issue. Thank you for fast help.
