### ISSUE TITLE
Render new JSON objects

### ISSUE THREAD

**Issue by matt-e-king** [minikomi/Bootstrap-Form-Builder#40]
Hey there! I LOVE this form builder. It's very flexible and a really fun application to build upon.

I was hoping you could help me with something. I would really like to re-output the JSON of the field object as attributes are changed. For instance:

The input.json file has the following object:

{
    "title": "Text Input",
    "fields": {
      "id": {
        "label": "ID / Name",
        "type": "input",
        "value": "textinput"
      },
      "label": {
        "label": "Label Text",
        "type": "input",
        "value": "Text Input"
      }....

But in the form builder, when I drop an Input into the left side and I changed the "Label" attribute to "First Name", I would really like to re-output a new JSON snippet that would look like this:

{
    "title": "Text Input",
    "fields": {
      "id": {
        "label": "ID / Name",
        "type": "input",
        "value": "textinput"
      },
      "label": {
        "label": "Label Text",
        "type": "input",
        "value": "First Name"       <------ the change would be reflected here
      }....

Is there a quick and dirty way to do this? Thanks for any assistance you are able to provide.

**Comment by minikomi** [comment]
Hey, this should be pretty easy because the whole created form is stored as a backbone model. I'll get back to you about this soon.

**Comment by yosephlodamo** [comment]
This is the best form builder I have seen so far!
I am hoping you will get back to this issue because I want to store the designed form in json format in a database and reload it later.
Thanks

**Comment by craighooghiem** [comment]
I had this working on the previous setup.
I'm going to look into adding it here and see if it makes sense.

Is the backbone stuff online yet or still in development?

**Comment by minikomi** [comment]
Add:

```
  this.collection.on("add", this.toJson, this);
  this.collection.on("remove", this.toJson, this);
  this.collection.on("change", this.toJson, this);
```

here: https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/views/my-form.js#L17

and:

```
, toJson: function() {
  console.log(this.collection.toJSON());

}
```

here: https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/views/my-form.js#L39

Open the console, and look at the output.
You should see the object which is used to create the form.

If you pass it in here:

https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/app.js#L49-L59

You can repopulate the form on creation.

**Comment by matt-e-king** [comment]
This is perfect! Thanks so much. Sorry for the late reply.

I have tested and it is working like a charm. I will be taking that JSON, storing it in a database and then reloading it dynamically into the "new MyFormSnippetsCollection" as you mentioned here:
https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/app.js#L49-L59

Thanks!

**Comment by zltqzj** [comment]
How to change form-builder  to multiple column?  thanks

**Comment by ND17** [comment]
To **minikomi**

in above you give ans in that you said that add some code in my-form.js
Add:

     this.collection.on("add", this.toJson, this);
     this.collection.on("remove", this.toJson, this);
     this.collection.on("change", this.toJson, this);

    , toJson: function() {
     console.log(this.collection.toJSON());

    }


Open the console, and look at the output.  i m follow ur instruction but in console there is no JSON object

**Comment by supreet888** [comment]
Hey 

I have got the Json object in console . But i want to know how are you passing the saved jSon object to App.js below code.


new MyFormView({
        title: "Original"
        , collection: new MyFormSnippetsCollection([
          { "title" : "Form Name"
            , "fields": {
              "name" : {
                "label"   : "Form Name"
                , "type"  : "input"
                , "value" : "Form Name"
              }
            }
          }
        ])
      });

**Comment by ghost** [comment]
@matt-e-king Hi i have checked yours solution. Its pretty neat. I just want to ask is there a way to reload the form using the Rendered HTML Code.
I would think it as : Parsing the HTML Code to Json Object and then passing the same json to your Load Json Area.

So is there a way we can parse the HTML to exact the same Json which already being created every time we drag the control
