### ISSUE TITLE
Select & Input Width

### ISSUE THREAD

**Issue by mmackh** [minikomi/Bootstrap-Form-Builder#41]
According to: https://github.com/twitter/bootstrap/issues/3413
`input-xlarge, input-xxlarge, etc.` are only there for legacy reasons.
I tripped on this issue because with the form builder, select and input have different sizes.
Is there a reason for still using the legacy css tags?

**Comment by minikomi** [comment]
There was no mention of that in the documentation, and when I created the
form builder I just followed the examples on bootstrap site.

It seems that bootstrap 3 is coming soon, so a lot will have to be redone..
I think this can wait until then.

On Thursday, July 25, 2013, Maximilian Mackh wrote:

> According to: twitter/bootstrap#3413https://github.com/twitter/bootstrap/issues/3413
> input-xlarge, input-xxlarge, etc. are only there for legacy reasons.
> I tripped on this issue because with the form builder, select and input
> have different sizes.
> Is there a reason for still using the legacy css tags?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/41
> .

## 

----=^.^=---

**Comment by minikomi** [comment]
Will fork & create new version.
