### ISSUE TITLE
Need help understanding

### ISSUE THREAD

**Issue by ghost** [minikomi/Bootstrap-Form-Builder#42]
I don't understand how to make my own edits by what is said in the Notes and adding new form elements sections.

**Comment by minikomi** [comment]
Well.. what have you tried?

**Comment by ghost** [comment]
First I changed the data-main <script data-main="assets/js/main-built.js" src="assets/js/lib/require.js" ></script> to point to assets/js/main.js 
Then to build.js (and I don't know what to do with the r.js). Then changed it to assets/js/main-built.js
And I didn't run the command bc I don't know what that is. 

I made a change to the about.html file and it still shows up as what it came with when I originaly downloaded

**Comment by minikomi** [comment]
Hmm. If you change the html and nothing changes, sounds like a caching issue. try disabling caching and try again.

**Comment by ghost** [comment]
I  have disable my cache in both Chrome and Firefox, but I don't see my changes..

**Comment by minikomi** [comment]
Even to html? This doesn't sound like something specific to the form
builder.

On Tue, Aug 13, 2013 at 11:38 PM, kleach notifications@github.com wrote:

> I have disable my cache in both Chrome and Firefox, but I don't see my
> changes..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/42#issuecomment-22569395
> .

## 

----=^.^=---

**Comment by ghost** [comment]
Here is what I have if you wanna check it out: https://github.com/kleach/Bootstrap-Form-Builder

**Comment by ghost** [comment]
DId my code work for you?
