### ISSUE TITLE
adding tab to the existing formbuilder adds the control tabs 

### ISSUE THREAD

**Issue by hardik-dave** [minikomi/Bootstrap-Form-Builder#43]
![tabs-bootstrap-display-error](https://f.cloud.github.com/assets/5189999/931267/d7d1fcb0-0028-11e3-9918-58a710f1d301.png)

I'm having problem when I use a new tab on the page where I have Form Builder code added. Basically, I'm trying to add a parent tab and show the form builder in one of the tab options of the parent tab. But if you see the screenshot, you will see both the tabs are showing tabs from form builder.

**Comment by minikomi** [comment]
OK, I made the tabs add to `#formtabs` .. just use a different id for your own.

**Comment by minikomi** [comment]
fixed .active tab to be unique to form builder too.
