### ISSUE TITLE
Need help with Reloading saved form definition in EDIT mode

### ISSUE THREAD

**Issue by hardik-dave** [minikomi/Bootstrap-Form-Builder#44]
Hey There,

First of all, thank you very much for a nice form builder. I love it. One more thanks for being so responsive on any issue doubt we ask you guys. 

This time, I need help/direction/pointers as to following:

1) I have generated the form. Now, I keep track of the rendered form html as well as the form html being updated/added while adding the new form. i.e. with "components" and without "components" attributes.

2) now, I saved this form in my database and I need to reload the previously created page. See the screenshot i see. I get one form and its fieldset form the saved definition form the database. And another fieldset tag gets added to this existing form. So what happens is that when i try adding new controls on this form, it adds those to the new form's new fieldset tag and not to my existing, previously created, loaded form's fieldtag. 

Hope this question explanation is clear to understand. Please see the screenshot below of what I see while loading this in Edit mode. 

![form_reload_issue](https://f.cloud.github.com/assets/5189999/949709/979ea94c-0382-11e3-9a85-232f91bdfbc4.png)

Thanks once again.

**Comment by minikomi** [comment]
This is beyond the scope of the form builder.

Look at https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/app.js#L49-L56 where a `MyFormView` is being created. You can pass it a collection of form objects to get the view

**Comment by mazen79** [comment]
hey dave did you find a solution to this problem i'm facing the same issue?

**Comment by minikomi** [comment]
Check out https://github.com/minikomi/Bootstrap-Form-Builder/issues/40#issuecomment-24131496

**Comment by hardik-dave** [comment]
Thanks minikomi, I already found the same solution earlier and sent you an email personally asking your permission to submit the changes, but anyway, thanks for your effort to make it available, i'm sure a lot of people will be benefited from this.

**Comment by minikomi** [comment]
I won't add it in to this version, but feel free to do what you like.

On Fri, Sep 13, 2013 at 6:15 PM, hardik-dave notifications@github.comwrote:

> Thanks minikomi, I already found the same solution earlier and sent you an
> email personally asking your permission to submit the changes, but anyway,
> thanks for your effort to make it available, i'm sure a lot of people will
> be benefited from this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/44#issuecomment-24382414
> .

## 

----=^.^=---

**Comment by ihabsoliman** [comment]
Hey hardik-dave
Can you tell me how you reloaded and saved the form from the database please?

**Comment by ankurngm** [comment]
If anyone of you guys have the snippet/solution/pointers, can you please share it here or some Wiki... I can see many people are trying to accomplish the same thing and are struck...

**Comment by qfard** [comment]
hardik-dave,

can you please share saving to and reloading from database?

TIA

**Comment by hardik-dave** [comment]
Sorry guys for late response, please let me know if you still need the help saving, retrieving the information.

**Comment by prestatr** [comment]
@hardik-dave yes I'm need this. How is to re-edit OR re-load saved form from database to bootstrap-form-builder.

**Comment by keyurcrest** [comment]
please give me solutions of the edit form functionality. I saved render htm code in database.please give me a solutions

**Comment by hiteshcrest** [comment]
@hardik-dave yes I'm need this. How is to re-edit OR re-load saved form from database to bootstrap-form-builder.

**Comment by Nehace40** [comment]
@hardik-dave  How to save data to database and retrive that data as edit form

**Comment by hardik-dave** [comment]
Sorry guys, been busy on a different project. @ND17  I will spare some time in couple of days and share my logic and possibly the code with you guys. For any quick information you need, please send me PM on hardikmdave at yahoo dot com
