### ISSUE TITLE
Use instance of the app object in the index.html file

### ISSUE THREAD

**Issue by hardik-dave** [minikomi/Bootstrap-Form-Builder#45]
I have written another handler refresh:function(),  in the app.js, just like initialize: function()...But I see that app object, that is initialized in the Main.js can't be accessible on the index.html file. Is there anyway i can use app object in the index.html so that i can call app.refresh() from there?

**Comment by minikomi** [comment]
This project uses require js and avoids declaring globals.

More info here: http://requirejs.org/

**Comment by hardik-dave** [comment]
ok one more question, hopefully last one.
Apology for bugging you so much, and thanks for quick responses. 

I have dragged like 4 different types of controls from the right tabs to the form pane. now, how can i get hte JSON format of this generated Form with recently dropped controls? I believe, i will have to do this in my-form.js where the render code is written. I need that form to be converted to JSON so that i can then take it and utilize it.

**Comment by hardik-dave** [comment]
nevermind, figured it out. Thanks once again.
