### ISSUE TITLE
Any support for Bootstrap 3?

### ISSUE THREAD

**Issue by aponxi** [minikomi/Bootstrap-Form-Builder#46]
Will you be updating this great piece of work to work with Bootstrap 3?

**Comment by minikomi** [comment]
Yep, it'll be a fork though. I think many people will stick with 2 for the time being...

**Comment by aponxi** [comment]
Thanks! if you could mention me or reference this issue when it's up I'd appreciate it!

**Comment by minikomi** [comment]
@aponxi no problem, i'll let you know.

**Comment by ghost** [comment]
Hi . Can you reference or let me know where I can find the bootstrap3 form builder that will be awesome.  Thanks 
Swagato Bhatta
email: admin@swagatobhatta.com

**Comment by ihabsoliman** [comment]
https://github.com/IhabSoliman/Bootstrap-Form-Builder
