### ISSUE TITLE
Support FieldSets

### ISSUE THREAD

**Issue by Rawgeek** [minikomi/Bootstrap-Form-Builder#47]
Would be nice to have fieldsets so that you could insert an element inside another sub-fieldset.

**Comment by minikomi** [comment]
How would you see this working?

**Comment by Rawgeek** [comment]
You should be able to drag the fieldset (empty box) in the main area and be able to drag fields inside that box. This will help creating rules later. eg. If field A containe 'abc' hide/show fieldset/field.

**Comment by pspeth** [comment]
I would love to see this feature as well.
It would be useful, and interesting to see nested elements.

**Comment by ghost** [comment]
Same here.

**Comment by aruld** [comment]
+1 for this feature. It would simplify grouping of form elements. Do you have plans to support this?

**Comment by huchister** [comment]
Same here. Need this feature absolutely. Would love to see it.

**Comment by siddarth-rajavelu** [comment]
Any improvement on this?
Thanks

**Comment by minikomi** [comment]
Not going to add it, sorry.
