### ISSUE TITLE
Can you add advanced widgets sample, like a calendar or something

### ISSUE THREAD

**Issue by aroof** [minikomi/Bootstrap-Form-Builder#48]
Hello, I love this, but need to integrate to other platform. I believe I can do a postback via the AJAX to make this work.

Can explain the layout and templating a little more for a noob, I have been reading underscore, the code, and backbone, and getting lost.

**Comment by minikomi** [comment]
Try exploring the my-form.js 

https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/views/my-form.js

using breakpoints and the js console.
