### ISSUE TITLE
Captcha field

### ISSUE THREAD

**Issue by pras100** [minikomi/Bootstrap-Form-Builder#49]
Hi, Thanks for this great app.
There is no captcha for forms to create free of spams while getting mails.
Is there any possibilities of captcha field for creating form fields in Bootstrap form builder.

**Comment by craighooghiem** [comment]
Bootstrap does not have captcha form types, so it doesn't make that much sense to include this.
Also, JS based captcha forms that have visible logic tend to be less secure than the alternative anyways. 

The code generated here should be phase 1 of your form project. 
Once the form is generated, add the captcha manually and properly and write your form processor script.

**Comment by minikomi** [comment]
Sorry, only bootstrap normal elements.
