### ISSUE TITLE
Bootstrap 3.0 compatibility

### ISSUE THREAD

**Issue by JanWerder** [minikomi/Bootstrap-Form-Builder#50]
Classes changed. 
i.e.:
.input-large -> .input-lg

**Comment by ihabsoliman** [comment]
https://github.com/IhabSoliman/Bootstrap-Form-Builder

I forked it and changed it to be bootstrap 3.0 compatible, you are welcome to fix any bugs you find

**Comment by minikomi** [comment]
Yeah I'll fork and create a bootstrap 3 version eventually. Thanks.

**Comment by llonchj** [comment]
Will be a good idea to implement "renderers" able to build a Bootstrap 2, or Bootstrap 3, or even other type of forms...

**Comment by hueitan** [comment]
@IhabSoliman  @minikomi  
Why don't you give a pull request to the author ?
