### ISSUE TITLE
reloading content of form for editing and offset of controls.

### ISSUE THREAD

**Issue by mazen79** [minikomi/Bootstrap-Form-Builder#52]
Thank you very much for this nice piece of code you have there. I am trying to use your bootstrap form builder to create dynamic forms saved to db. I'm runnning into a small issue when i'm trying to reload the saved code into the form builder to edit my saved forms. The code is loading correctly into the right div and the fieldset is created but it seems that another fieldset is being created when you try to add any control to the existing form. Can you advise on this issue.
I believe it has something to do with how the form is loading. I'm doing most of the work on the client side. Simply loading my data into hidden fields and then setting the html value of the target div using javascript.

Another issue i'm facing is the offset or the placement of new controls into the form. When i'm placing a control i have to move it up so it can be displayed down the form!!! :-).  i'm using the form builder in a dotnetnuke site so i already have a <body> tag for the page which is what is causing the issue i believe. But i can put my finger on where i can set the top value correctly so the controls can be placed correctly into the form.

Thanks for any help you may offer

**Comment by ihabsoliman** [comment]
Hey,
Can you share your code that you use to reload the content back to the form and we can work together to fix this error you are getting.
and we can add it to this too,
Thats my fork of this project using bootstrap 3
 https://github.com/IhabSoliman/Bootstrap-Form-Builder

**Comment by minikomi** [comment]
https://github.com/minikomi/Bootstrap-Form-Builder/issues/40#issuecomment-24131496

**Comment by mazen79** [comment]
I'm using asp.net for my code and loading the content of the saved #render  into a hiddenField. Then i'm using a javascript function to simply copy the content of the hiddenField to #target.
the script is as follows:
    function CopyToEdit(HdnFldID) {
        var hdEdit = $("." + HdnFldID).val()
        $("#target").html(hdEdit);
    }

It's loading correctly to the page but i cannot edit it.
