### ISSUE TITLE
Inline Radios and Multiple Radios conflict

### ISSUE THREAD

**Issue by mazen79** [minikomi/Bootstrap-Form-Builder#53]
If a form has these two elements they're conflicting, one resets the other.

**Comment by minikomi** [comment]
Can you give a more specific example of how to recreate the bug?

**Comment by minikomi** [comment]
@mazen79 I tried but couldn't reproduce.. can you give specific instructions?

**Comment by mazen79** [comment]
Simply add the 2 controls to a single form and view the html. One will reset the other.

**Comment by minikomi** [comment]
What exactly do you mean by reset?

**Comment by mazen79** [comment]
One of them has no value selected.

**Comment by minikomi** [comment]
You need to set the id/name so that it is unique for each form element.

On Mon, Sep 16, 2013 at 3:17 PM, mazen79 notifications@github.com wrote:

> One of them has no value selected.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/minikomi/Bootstrap-Form-Builder/issues/53#issuecomment-24490661
> .

## 

----=^.^=---

**Comment by mazen79** [comment]
How exactly can i do that using the form builder? shouldn't the id/name be set at form creation. 
I already created something similar using a script for setting names at page load but only for labels.

**Comment by minikomi** [comment]
Click on an element and edit the ID/Name or group name attribute.

**Comment by mazen79** [comment]
Yeah i know but the interface i have created will be used by users on my portal so they won't probably set the ID for these elements. I should have it by default set to some random id. Thanks for the help anyway.

**Comment by mazen79** [comment]
changing the group name value will fix this issue for me. They were both set to the same value "radios".
