### ISSUE TITLE
Yaml parsing problem

### ISSUE THREAD

**Issue by LeenVandelied** [minikomi/Bootstrap-Form-Builder#55]
Hello,
   I've a problem when I try to do : 
 ruby parse.rb

--> parse.rb:3:in `require': no such file to load -- json (LoadError)
    from parse.rb:3

Line 3 is : require "json"

So i've tried to install :
    sudo gem install json

--> Building native extensions.  This could take a while...
ERROR:  Error installing json:
    ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:1:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.0 for inspection.

Trying to re-install ruby by : 

sudo apt-get install ruby1.9.1-dev

--> no problem 

retry install json :  It's work ! but when I retry : 
   ruby parse.rb

--> always the same error.

I don't find any solutions, if you can help me.

Best regards.

**Comment by minikomi** [comment]
That's more of a ruby environment problem.
