### ISSUE TITLE
Add a generic placeholder

### ISSUE THREAD

**Issue by freddyheppell** [minikomi/Bootstrap-Form-Builder#59]
If people want to include things like CAPTCHAs in their form it can be difficult to work out the formatting, so I think you should come up with some kind of generic placeholder, It would have label text and help text and in the code it would say something like 'Insert your content here'. This would also cover a range of other uses, not just captchas

**Comment by minikomi** [comment]
The formatting is standard Bootstrap. You can already do this with, say, a text input item.
