### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by webdaily** [minikomi/Bootstrap-Form-Builder#60]
The index.html has:

<script data-main="assets/js/main-built.js" src="assets/js/lib/require.js"></script>

We made changes (added a field) as instructed and then built the file using build.js

All works and we can see the main-built.js file has the changes BUT the new field is not there. The json changes come through but the form is not rendered on the page  - the OLD original form is always there no matter what. 

The instructions for the require steps are a little vague.

**Comment by minikomi** [comment]
Not sure what you're saying? You tried to add something but couldn't.. The original form is defined in app.js

https://github.com/minikomi/Bootstrap-Form-Builder/blob/gh-pages/assets/js/app.js#L47-L60
