### ISSUE TITLE
File Input Form Attribute

### ISSUE THREAD

**Issue by jmbuytaert** [minikomi/Bootstrap-Form-Builder#61]
Hi!

First, great idea to build this. Such a time-saver!

I was wondering if there's any way to add enctype="multipart/form-data" in the <form> whenever a File Input is added to the form?

Thanks!

**Comment by minikomi** [comment]
Good idea. Will add it in at some point.

**Comment by shethnc** [comment]
Is there's any way to add enctype="multipart/form-data" ?

**Comment by minikomi** [comment]
496f186a3d6ecf0c178cfa8c108eec173f077a26
