### ISSUE TITLE
Rendered source code from textarea

### ISSUE THREAD

**Issue by AlexSamir** [minikomi/Bootstrap-Form-Builder#64]
Hi, I'm trying to get the rendered source code from textarea but it seems that the text area doesnt have anything in it. could you tell me how can I get the code that is generated from the form builder?.
Thanks in advance..

**Comment by minikomi** [comment]
Browser version?

**Comment by hussv1** [comment]
What i do is set the value to a hidden text area in my form.
Edit the file my-form.js
In the render section you may add code to populate your hidden textarea with the rendered code.
Cheers

**Comment by minikomi** [comment]
I don't know what your issue is.
