### ISSUE TITLE
Popover properties / Remove certain properties

### ISSUE THREAD

**Issue by hussv1** [minikomi/Bootstrap-Form-Builder#65]
Hi,
Great Job btw. My question is how do I go about removing the ID/Name property from the popover?
Do i need to remove from the input text yaml file then recompile?
would that remove the ID/Name property from the json. I still need the property I just don't want the user to have access to this property. I hope I am making sense.

**Comment by hussv1** [comment]
OR is there a way to make the property read only?

Thanks

**Comment by hussv1** [comment]
I figured it out. in the popover template I added an if statement for id field made that read only.

**Comment by aruld** [comment]
@hussv1 Could you share the code that makes the attribute readonly? I have a similar requirement. Thanks.

**Comment by minikomi** [comment]
Add readonly attribute to the input element http://www.w3schools.com/tags/att_input_readonly.asp
