### ISSUE TITLE
adding and removing tab

### ISSUE THREAD

**Issue by kalpitpandit** [minikomi/Bootstrap-Form-Builder#66]
First of thanks Devs for making such a great Builder..

i want to hide rendered and buttons tab in that.. i tried to remove from app.js but it didn't get effected. So i followed readme.md steps for development and debugging.. 

i changed data-main like this 

data-main="assets/js/main.js" src="assets/js/lib/require.js" 
but getting XmlHttp Request error like follow 

XMLHttpRequest cannot load file:///C:/Users/Kalpit/Downloads/Bootstrap-Form-Builder-gh-pages/Bootstrap-Form-Builder-gh-pages/assets/js/data/input.json. Cross origin requests are only supported for HTTP. text.js:288
Uncaught NetworkError: A network error occurred. text.js:288

what's going wrong with it?  Can anyone suggest me..

**Comment by minikomi** [comment]
You need to use a local web server.

Try python -m SimpleHTTPServer 8000 and go to localhost:8000
