### ISSUE TITLE
Retain popup effects of elements

### ISSUE THREAD

**Issue by bhavya-nick** [minikomi/Bootstrap-Form-Builder#67]
I am thinking of utilizing this awesome work in an extension.
But i have certain queries regarding the effects.

I would like to save the created form and want to maintain the popup effects with the saved html content(snippets).

Since saving the html content and rendering back does not display the popup effects on clicking...is there any solution for that?

Thanks

**Comment by minikomi** [comment]
Not in scope for this repository.
