### ISSUE TITLE
HTML5 Validation attributes 

### ISSUE THREAD

**Issue by Iristyle** [minikomi/Bootstrap-Form-Builder#7]
It would be really nice if there were a way to turn on / off HTML5 validation attributes.

**Comment by craighooghiem** [comment]
This wouldn't be that difficult to implement. Which validation attributes do you want added/removed specifically?
Or are you just referring to things like required, email, etc?

**Comment by Iristyle** [comment]
Yeah, attributes like `required`, new input types, etc.
http://caniuse.com/#feat=forms

Here's another decent table on the state of HTML5 forms
http://wufoo.com/html5/

**Comment by craighooghiem** [comment]
Waiting until after the weekend to look at this. Minikomi discussing some overhaul changes.

**Comment by minikomi** [comment]
I've started modularizing the snippets into underscore templates, in preparation for converting this to a backbone.js app:

``` html
<div class="control-group component" data-type="search" rel="popover" title="Search Input" trigger="manual"                                                                                      
  data-content="<%=
  popoverTemplate({items: [
    {label: 'Label Text'  , type: 'text' , id: 'label'       , value: label },
    {label: 'Placeholder' , type: 'text' , id: 'placeholder' , value: placeholder },
    {label: 'Help Text'   , type: 'text' , id: 'help'        , value: helptext }
    ]})                      
  %>"
  >
  <!-- Text input-->
  <label class="control-label valtype" for="input01" data-valtype='label'><%= label %></label>
  <div class="controls">
    <input type="text" placeholder="<%= placeholder %>" class="input-xlarge valtype" data-valtype="placeholder" >
    <p class="help-block valtype" data-valtype='help'><%= helptext %></p>
  </div>
</div>
```

That way things will be much easier to add / keep up with the main bootstrap version.
Popover options can be type text, textarea, select, checkbox etc. each with their own respective templates.
It's a bit of a mess at the moment but I'll put up another branch when things start to get organized. Been wrapping my head around how I want to lay this out in backbone so it's taking a little longer than expected.

**Comment by craighooghiem** [comment]
This makes sense. I think it's a good way to do it.
I'm not so sure about the backbone part, but if it works then that's perfect for most people.

**Comment by minikomi** [comment]
OK I added required as a checkbox for the input elements.

**Comment by minikomi** [comment]
I'm hesitant to add too many of these, I think things like validation patterns are better added to the generated source. I don't want the popup to be too cluttered.

**Comment by ghost** [comment]
First of all, thank you for this nice tool!!

How about adding more types like "email", "number", "url" and so on... ? I would also be happy to see the possibility to set a specific pattern for a form field.

**edit:**
If it's possible, please remove unused elements from the final code, like the help-element.

**Comment by minikomi** [comment]
Please create a separate issues for these requests. I'm not convinced validation patterns belong in the basic form builder, but a dropdown to select "type" eg. text, email, url sounds good.
