### ISSUE TITLE
How to edit form?

### ISSUE THREAD

**Issue by kalpitpandit** [minikomi/Bootstrap-Form-Builder#70]
i have created form and now i want to edit this form again..

is it possible?

**Comment by zltqzj** [comment]
I am trying this now. but not success.
1、change the index.html to index.jsp 
2、 change this
 <% 
 String str1 = "{title:'Form Name',fields:{name:{label:'Form Name',type:'input',value:'Form Name'}}}"; 
 String str2 = "{title:'Text Area',fields:{id:{label:'ID / Name',type:'input',value:'Text Area'},label:{label:'Label Text',type:'input',value:'Text Area'},textarea:{label:'Starting Text',type:'textarea',value:'Default Text'}}}";
 %>

  <script>
  var initControls = [<%=str1+","+str2 %>];
  </script>

str1 str2,you can select database to get it .
That's my opinion.

**Comment by minikomi** [comment]
https://github.com/minikomi/Bootstrap-Form-Builder/issues/40#issuecomment-24131496

**Comment by kalpitpandit** [comment]
hi,

thanks for replaying.. actually i am using PHP as my backend language so i
can go with jsp files...

still i am trying to do edit but no success...

i am suggesting you please make this one as open issue so everyone come to
know and they will give their try also..

Thanks

**Comment by minikomi** [comment]
It's not an issue with this repository. If you want to fork it, create an app on top of it which can read and save forms from a database, feel free to do so.
