### ISSUE TITLE
Bootstrap 3.x support

### ISSUE THREAD

**Issue by victorhaggqvist** [minikomi/Bootstrap-Form-Builder#71]

**Comment by ihabsoliman** [comment]
https://github.com/IhabSoliman/Bootstrap-Form-Builder

I forked the original project and added 3.x support, its not full and some bugs but feel free to fix anything you find and commit it.

I personally don't have that much time now to update or fix it.

**Comment by akoskm** [comment]
Why don't you create a pull request for this one?

**Comment by tanwaniniranjan** [comment]
https://bountify.co/new-version-of-bootstrap-formbuilder-in-v3
