### ISSUE TITLE
Could be more lazy-prototyping friendly

### ISSUE THREAD

**Issue by JawnzWoerk** [minikomi/Bootstrap-Form-Builder#77]
How to reproduce:
1: Drag'n'drop a few TextInput
2: Check Rendered tab

Expected result:
The IDs wouldn't be duplicate like having 3 "textinput", but rather:
textinput(1?)
textinput2
textinput3
textinput4

Actual result:
textinput, textinput, textinput

**Comment by minikomi** [comment]
Yep, this is fixed.
