### ISSUE TITLE
Could you add box feature where you can add sub-items inside of that box?

### ISSUE THREAD

**Issue by huchister** [minikomi/Bootstrap-Form-Builder#79]
It would be nice to have div wrapper that you can add sub items inside of the boxes.

For instance, there is new snippet item call div with empty div box. 

If you drag box creates simple div tag that can hold input fields, textareas for that box only aka subitems. 

Something like this.

![image](https://cloud.githubusercontent.com/assets/3429867/2605607/22d1232a-bb46-11e3-946a-b57b7446560f.png)

**Comment by sagikazarmark** [comment]
+1 for this. IMO it is better to call it fieldset.

**Comment by sagikazarmark** [comment]
Same as #47

**Comment by minikomi** [comment]
No, this project is too simple for this.
