### ISSUE TITLE
Script validations

### ISSUE THREAD

**Issue by Iristyle** [minikomi/Bootstrap-Form-Builder#8]
This one is tough, not sure how to implement.

But it would be nice to hook up standard / unobtrusive / maintainable validators for each form element.

Not sure if the best solution would be to depend on a polyfill to support all browsers.
https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills

Just throwing ideas out there, but it would be useful to make this a more full-featured form designer.

**Comment by minikomi** [comment]
This is something better served by another library, and added later.
