### ISSUE TITLE
How to save as collection as JSON and re-populate form from it?

### ISSUE THREAD

**Issue by ankurngm** [minikomi/Bootstrap-Form-Builder#81]
I need to accomplish the following:
1. Create form using "minikomi/Bootstrap-Form-Builder" plugin.
2. Save the generated collection as JSON/YAML (in database).
3. Re-create the form using the saved information from database.

Please share any pointers/snippet. I can't find a thing in wiki regarding it.

**Comment by jolamar** [comment]
+1 for this feature

**Comment by ankurngm** [comment]
Not sure about this library, but you can easily accomplish it via AngularJs. Have you tried exploring that?
