### ISSUE TITLE
Not able to use

### ISSUE THREAD

**Issue by Sanchaita** [minikomi/Bootstrap-Form-Builder#84]
Hello 

Can anyone help me in using the Bootstrap-Form-Builder.
I have been trying to use this since a whole day, but I failed.
I don't understand how will the file be saved and how will the user refer to it.

Regards

**Comment by mcrayne** [comment]
Look in the Rendered tab for the HTML snippet you can use for your form. You will need to copy(all)-paste from this tab into your app. (Ctrl-A, Ctrl-C, then Ctrl-V where you want the form in your app). Your app will need to include the Bootstrap CSS and JS files for the form to look and feel like it does in the Bootstrap-Form-Builder.

See the discussion at https://github.com/minikomi/Bootstrap-Form-Builder/issues/40 for forks addressing the saving and retrieving of the form definition.

**Comment by minikomi** [comment]
Thanks mcrayne
