### ISSUE TITLE
Save to database & re-edit? Has anyone been able to do it?

### ISSUE THREAD

**Issue by qfard** [minikomi/Bootstrap-Form-Builder#85]
Hello all,

I just found this code base and it seems to be a great product and it is what I have been looking for.

I guess the subject says it all, how can I save the HTML code to database and then re-edit it.  Code snippet would be much appreciated.  

I can be in JSON, PHP, ASP or any language.

Thanks...Q

**Comment by mbchandar** [comment]
store the instance of MyFormView in a variable and convert the form collection to json and save it.

**Comment by qfard** [comment]
thanks.

before I do that, is there way to bring it back and re-edit the form?

**Comment by mbchandar** [comment]
yes. store the json in db. reload the json from db and give it to the collection as input

**Comment by qfard** [comment]
is there a sample code somewhere or tutorial I could follow? I am really new to this

**Comment by ibanez0r** [comment]
sample code -> http://www.php.net/manual/en/function.serialize.php

**Comment by qfard** [comment]
no i didn't mean sample of serialize - i meant sample of the serialize, json, saving and retrieving it back...  willing to pay for your time for sample too...

**Comment by ibanez0r** [comment]
hehe, its really not too hard m8, im sure if u have a look around you will find full working examples of how to do it in existing form building web plugins for wordpress etc, i will have a try later on tonight and see if i can do it ok! and ill post back here later to let you know how i go.

**Comment by mbchandar** [comment]
you are doing it in PHP?

**Comment by ibanez0r** [comment]
I will try, sure!

**Comment by qfard** [comment]
I can do the page in PHP or ASP... I want to have it display on the page and have a lightbox popup for edit mode and the popup can be in PHP or ASP.

thanks guys.

**Comment by ibanez0r** [comment]
Well i had a quick look into doing this, i am too busy sadly tonight to do the entire script but i can give an example of how to save your form then load it, i will fork this and post tomorrow at some point a full working example. as its really not very complex i dont req any payment brother.

**Comment by qfard** [comment]
i really appreciate your help.  one day when we are in the same city, I'll buy you a beer or two... BTW, I am in Philadelphia area

**Comment by ibanez0r** [comment]
So just an update m8 i managed to save the form as a serialized string that u could convert to json etc, very easily, having a few issues loading the form atm, tho i think i can prob figure it out. will keep u posted!

**Comment by qfard** [comment]
thanks and my offer stands - i am really new to backbone and have only done one other JSON call - so really new here...

**Comment by mbchandar** [comment]
it can be done.
- balachandar muruganantham
  எனது தமிழ் பக்கங்கள் - http://www.balachandar.net/pakkangal
  தமிழ் புத்தக விற்பனை இணையம் - http://www.chennaishopping.com/ - 450ரூ மேல்
  உள்ள ஆர்டர்களுக்கு, இலவச சேர்க்கை.
  தமிழ்ச் சொல் திருத்தி -
  https://addons.mozilla.org/en-US/firefox/addon/tamil-spell-checker-for-firefo/

2GB space + 20 GB B/W + cPanel, LAMP Hosting http://www.vazhangi.com/

**Comment by qfard** [comment]
how? have you done it?  I don't know backbone
