### ISSUE TITLE
Changing "Title" value in select.json fails the load

### ISSUE THREAD

**Issue by mcrayne** [minikomi/Bootstrap-Form-Builder#86]
I wanted to add a basic select input with US States already loaded. I copied the selectbasic object and changed the options to include some states, changed the id to selectstate and changed the label to "Select State". Worked fine. When I change the "Title" property to "Select State" the index.html stops loading at the Select tab. 

What is the use of the "title:" property in select.json? Actually, changing the "title": value in any of the .json files fails the load at that point.

![image](https://cloud.githubusercontent.com/assets/3066333/3047212/9d3fc26c-e132-11e3-8ffb-b9bad20a6edf.png)

**Comment by mcrayne** [comment]
There is no problem here. Though, your instructions for adding a new element should emphasize that the "title": value used in the .json file must match the name of the snippet .html file and when adding to the snippet-templates.js file add the require in both place of the define method.

This seems pretty fragile. Can you refactor to remove this magic (using a regex to convert the "title": to all lower case, no whitespace but then using the "title": property as is to title the popover?

**Comment by minikomi** [comment]
Hmm. Thanks for pointing it out, you're right, I just made this for myself so I didn't take into consideration people extending it. Maybe each snippet should have a `snippet-name:` field.
