### ISSUE TITLE
Support for Grid / Column

### ISSUE THREAD

**Issue by mbchandar** [minikomi/Bootstrap-Form-Builder#87]
How do i place an element in line or in grid form?

any reference? I want to place three textbox in a row for 10 rows. how to do that?

**Comment by gopal333** [comment]
http://getbootstrap.com/css/
check Here...

**Comment by mbchandar** [comment]
@gopal333 hope you understood my question. i want to design form with grid in form builder. any possibility or idea?

**Comment by gopal333** [comment]
I think it is not possible to built such form in Form Builder.
You have To do it by hard coding by using span tag.

**Comment by krkmzugur** [comment]
2014-05-24 11:14 GMT+03:00 gopal333 notifications@github.com:

**Comment by minikomi** [comment]
Not going to happen.
