### ISSUE TITLE
Save to database & re-edit? Has anyone been able to do it?

### ISSUE THREAD

**Issue by qfard** [minikomi/Bootstrap-Form-Builder#88]
This is so close to what I need for my project that I can't let it go...

would someone give me an estimate how much they are willing to charge to store the HTML to MySQL and open and re-edit it?

thanks.

**Comment by sohelrana820** [comment]
@qfard  Do you still looking for the solution? I can help you in this case. If you need any help you can knock me.

Thanks

**Comment by qfard** [comment]
i am working at it right now but do need help...my email is qfard<at>inbox<dot>com -----Original Message-----From: notifications@github.comSent: Thu, 12 Jun 2014 00:47:35 -0700To: bootstrap-form-builder@noreply.github.comSubject: Re: [Bootstrap-Form-Builder] Save to database & re-edit? Has anyone been able to do it? (#88)@qfard  Do you still looking for the solution? I can help you in this case. If you need any help you can knock me.

Thanks

—Reply to this email directly or view it on GitHub.

Free Online Photosharing - Share your photos online with your friends and family!
Visit http://www.inbox.com/photosharing to find out more!

**Comment by minikomi** [comment]
Outside scope of project. Please fork.
