### ISSUE TITLE
editing in visual studio

### ISSUE THREAD

**Issue by razisyed** [minikomi/Bootstrap-Form-Builder#89]
Thanks for this tool.

I tried the readme.md steps for development and debugging and changed data-main to "main.js"

data-main="assets/js/main.js" src="assets/js/lib/require.js" 

I'm debugging in visual studio, and I get this error:

assets/js/lib/../data/input.json HTTP status: 404

Any ideas on how to resolve it?

Thanks

**Comment by razisyed** [comment]
Btw, I tried adjusting the paths in main.js. I removed the baseUrl and used relative path instead of "..", and got:

http://requirejs.org/docs/errors.html#scripterror

**Comment by minikomi** [comment]
Use a web server in the root of the project.

**Comment by profscot** [comment]
I am having the same problem as razisyed and I cannot understand minikomi's response made on Oct 9th 2014.  Can you help?

**Comment by SachinNambiar** [comment]
http://pastebin.com/Rwevbcj5
It is caused because IIS is blocking static JSON. Add this to webconfig to solve the problem.
