### ISSUE TITLE
Multiple elements on one line, Headers & Line Breaks

### ISSUE THREAD

**Issue by qfard** [minikomi/Bootstrap-Form-Builder#91]
Hi There,

First, great product.... In my version, I am able to save the elements to MySQL and reload the form from there - very nicely done.

Just need some niceties to make it perfect for us.  Would appreciate direction and/or hints on how to do it.

1- put multiple elements in one line - for example:

Name:      [first name]  [last name]
or
Address:  [Address Line 1]
                [Address Line 2]
                [City] [State] [Zip]

2- add text header boxes - somewhere to put instructions and other text without any field.

3- add line beaks to group elements vertically.

Thank you in advance for your attention on this.

Q

**Comment by minikomi** [comment]
Sorry, only simple horizontal forms. Not a product either - just a simple tool.

**Comment by qfard** [comment]
Thanks.  Great product.

Just in case someone else needs/wants it, I have solved it, contact me for the code.

Below is a new tab I create that has some useful stuff like:

1- heading
2- horizontal line
3- line break
4- first name / last name on single line
5- full address widget

![image](https://cloud.githubusercontent.com/assets/7560371/3576067/a4750840-0b8e-11e4-9ff5-6b370c7e082a.png)

**Comment by siddarth-rajavelu** [comment]
HI qfard,
I'm very interested in this feature. 
Can you send me the link to the code. srajavel@uci.edu.

Thanks 
Siddarth

**Comment by tariq-mahmood-dev** [comment]
Hi qfard,
can you please send me your updated plugin on email: tariq.mahmood_2@yahoo.com

Thanks

**Comment by tariq-mahmood-dev** [comment]
Hi qfard I still need your changes, can you please send me

**Comment by kaoshen** [comment]
@qfard @siddarth-rajavelu @tariq-mahmood-nxb @itsazzad  
can anyone sent this to me on email:kaotudou2015@163.com
Thanks.

**Comment by ameeradnan** [comment]
@qfard @siddarth-rajavelu @tariq-mahmood-nxb @itsazzad

can any of you guys send me thechanges related to this issue? thanks

ameeradnan@gmail.com
