### ISSUE TITLE
blank or line on popover using JSON/YAML file

### ISSUE THREAD

**Issue by qfard** [minikomi/Bootstrap-Form-Builder#92]
Hi,  is it possible to put a blank line and/or <hr> in between fields in the popover?

I am trying to follow the JSON and YAML files but can't figure out if there is such an option or not.

thanks.

![image](https://cloud.githubusercontent.com/assets/7560371/3648989/7020419c-110e-11e4-8933-eb4565c8a3f6.png)

**Comment by qfard** [comment]
does anyone know what can create a blank or <hr> in the popup?

**Comment by minikomi** [comment]
It's possible, but not relevant to this project.
