### ISSUE TITLE
Adding single quote in Multiple Radios label breaks edit

### ISSUE THREAD

**Issue by rtpHarry** [minikomi/Bootstrap-Form-Builder#93]
I just set the label of a Multiple Radios label to "I'm interested in".

Then I realised I hadn't put the caps on the words, went back to edit and the label just said "I"

Assume this will probably happen with all labels?

Sorry for quick bug report but working to a deadline at the moment :)

**Comment by minikomi** [comment]
Thank you. I fixed escaping in a bunch of templates.
