### ISSUE TITLE
Make it clear this is a Bootstrap v2 tool!

### ISSUE THREAD

**Issue by rtpHarry** [minikomi/Bootstrap-Form-Builder#94]
Great tool, little annoyed with myself and the documentation that this didn't really point out that it was a Bootstrap v2 tool :)

My own fault for not checking but you could help people out by putting a big warning at the top.

I managed to convert most of the code over using this tool:

http://code.divshot.com/bootstrap3_upgrader/

(Just failed on textarea tag)

**Comment by KrunchMuffin** [comment]
Did you post it back to github for others?

**Comment by rtpHarry** [comment]
Not sure what you mean - I didn't make the code in my link.

However you have reminded me that I did eventually find a Bootstrap v3 port of this code tucked away in somebodies dropbox account: 

https://dl.dropboxusercontent.com/u/1656247/bfb/index.html

Hopefully that helps people

**Comment by minikomi** [comment]
It was there in about the 3rd line of the Readme, but I updated the actual site too.
